server:
  port: 8081
spring:
  application:
    name: gym-report
  data:
    redis:
      url: redis://redis:6379
      username: default
      password: redis
      repositories:
        enabled: false