server:
  port: 0
spring:
  application:
    name: gym-report
  data:
    redis:
      url: redis://redis:6379
      username: default
      password: redis
      repositories:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        preferIpAddress: true

#ACTUATOR CONFIGURATION
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'