#SELECT COMMUNICATION BETWEEN SERVICES (CAN BE CHANGED LIKE ENV IN DA DOCKER-COMPOSE)
INTERACTION_BETWEEN_MICROSERVICES: feign
NOSQL_TYPE: mongo
application:
  #MESSAGING QUEUE'S CONFIGURATION
  messaging:
    queue:
      workload: trainerWorkloadQueue
      trainer-summary:
        response: trainerSummaryResponseQueue
        request: trainerSummaryRequestQueue

#SERVICE PORT 0=RANDOM PORT
server:
  port: 0

#LOGGING PATTERN
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT:yyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{correlationId:- } %msg%n"

spring:
  #APP ID
  application:
    name: gym-report

  data:
    #REDIS CONFIG
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      username: default
      password: redis
      repositories:
        enabled: false
    #MONGODB CONFIGURATION
    mongodb:
      uri: "mongodb://${MONGODB_USER:mongodb}:${MONGODB_PASSWORD:mongodb}@${MONGODB_HOSTS:localhost:27017}"
      database: "${MONGODB_DATABASE:gym_db}"
      replica-set-name: "${MONGODB_RS:rs0}"
      auto-index-creation: true
  #CIRCUIT BREAKER
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
        alphanumeric-ids:
          enabled: true
      client:
        config:
          gym-main:
            read-timeout: 2000
            connect-timeout: 1000
  #ACTIVEMQ
  artemis:
    user: activemq
    password: activemq
    broker-url: tcp://${ACTIVEMQ_URI:localhost}:61616
  jms:
    template:
      receive-timeout: 10000

#CIRCUIT BREAKER
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      GymMainClientvalidateTokenStringString:
        minimumNumberOfCalls: 6
        failureRateThreshold: 50
        ignoreExceptions:
          - com.example.gymreport.exceptions.UnauthorizedException
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

#EUREKA DISCOVERY CLIENT CONFIGURATION
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URI:localhost}:8761/eureka
  instance:
    preferIpAddress: true

#ACTUATOR CONFIGURATION
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'